### ISSUE TITLE
infografía 

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/infografia-Nayee123#2]
[infografía Nayeli Anai González López.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Nayee123/files/7147273/infografia.Nayeli.Anai.Gonzalez.Lopez.pdf)

**Comment by Lissete7** [comment]
Calificación: 18 pts/20

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
